regions:
  - "northamerica-northeast1"
  - "us-central1"

forwarding_rule:
  port_range: "443"
  allow_global_access: true

cloudrun_services:
  - name: "fetch-data"
  - name: "delete-data"
  - name: "create-data"
  - name: "checkout-data"
